repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.9 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terraform-fmt
    - id: terraform-validate
    - id: shellcheck
