# Copyright 2019 The Tranquility Base Authors
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for itop-istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vbkunin/itop
  tag: 2.6.1-base
  pullPolicy: IfNotPresent

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# ClusterIP - is the default, use this when the Istio Gateway is enabled
service:
  type: ClusterIP
  port: 80

# Using istio instead
# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []

#   tls: []
#     - secretName: chart-example-tls
#       hosts:
#         - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Expecting a String in this format
# "/cloud_sql_proxy",
# "-instances=project-poc-02:us-central1:itop-db-01=tcp:3306",
# "-credential_file=/secrets/cloudsql/credentials.json"
cloudSqlProxySidecar:
  image: gcr.io/cloudsql-docker/gce-proxy:1.11
  instanceConnectionName: null
  dbPort: 3306

gateway:
  ## Set to true to enable gateway record generation
  enabled: true
  name: itop-gateway
  portNumber: 80
  portName: http
  portProtocol: HTTP

istioServiceEntry:
  cloudSqlInstanceIp: null
  cloudSqlInstancePort: 3307 # at the moment, Google Cloud SQL always available on port 3307
